In [1]:
import pandas as pd

In [2]:
weather_data_raw_df = pd.read_csv(r'../data/raw/weatherData.csv')

In [14]:
weather_data_raw_df

,location_id,date,weather_code (wmo code),temperature_2m_max (°C),temperature_2m_min (°C),temperature_2m_mean (°C),apparent_temperature_max (°C),apparent_temperature_min (°C),apparent_temperature_mean (°C),daylight_duration (s),...,precipitation_sum (mm),rain_sum (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_gusts_10m_max (km/h),wind_direction_10m_dominant (°),shortwave_radiation_sum (MJ/m²),et0_fao_evapotranspiration (mm),sunrise,sunset
0,0,1/1/2010,1,30.1,22.6,26.0,34.5,25.0,29.0,42220.20,...,0.0,0.0,0,12.2,27.4,19,20.92,4.61,06:22,18:05
1,0,1/2/2010,51,30.1,23.7,26.3,33.9,26.1,29.7,42225.71,...,0.1,0.1,1,13.0,27.0,24,17.71,3.91,06:22,18:06
2,0,1/3/2010,51,29.6,23.1,26.0,34.5,26.2,29.9,42231.68,...,0.6,0.6,3,12.3,27.4,17,17.76,3.66,06:22,18:06
3,0,1/4/2010,2,28.9,23.1,25.7,31.7,26.1,28.4,42238.11,...,0.0,0.0,0,17.0,34.6,357,16.50,3.75,06:23,18:07
4,0,1/5/2010,1,28.1,21.3,24.6,30.0,22.9,26.2,42244.99,...,0.0,0.0,0,18.7,37.1,353,23.61,5.00,06:23,18:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142366,26,6/4/2024,53,24.4,18.2,21.2,28.6,19.8,23.9,45005.79,...,1.7,1.7,8,11.3,27.4,210,21.33,3.83,05:49,18:19
142367,26,6/5/2024,51,24.9,18.9,21.1,29.1,20.5,23.5,45013.46,...,1.4,1.4,8,13.1,30.6,209,20.28,3.62,05:49,18:19
142368,26,6/6/2024,53,24.3,16.9,20.4,28.1,17.6,22.6,45020.70,...,1.8,1.8,10,10.9,27.7,203,20.02,3.61,05:49,18:19
142369,26,6/7/2024,53,23.9,18.9,20.9,27.5,20.7,23.5,45027.51,...,4.3,4.3,14,11.9,29.2,200,18.74,3.33,05:49,18:20
142370,26,6/8/2024,51,24.7,17.2,20.6,27.1,18.3,22.3,45033.88,...,1.0,1.0,4,17.4,37.4,212,20.37,3.56,05:49,18:20

In [8]:
weather_data_date_parsed_df = weather_data_raw_df.copy()
weather_data_date_parsed_df['date'] = pd.to_datetime(weather_data_raw_df['date'], format='%m/%d/%Y')

In [9]:
weather_data_may_df = weather_data_date_parsed_df[weather_data_date_parsed_df['date'].dt.month == 5]

In [10]:
weather_data_may_df

,location_id,date,weather_code (wmo code),temperature_2m_max (°C),temperature_2m_min (°C),temperature_2m_mean (°C),apparent_temperature_max (°C),apparent_temperature_min (°C),apparent_temperature_mean (°C),daylight_duration (s),...,precipitation_sum (mm),rain_sum (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_gusts_10m_max (km/h),wind_direction_10m_dominant (°),shortwave_radiation_sum (MJ/m²),et0_fao_evapotranspiration (mm),sunrise,sunset
120,0,2010-05-01,61,31.1,25.1,27.7,37.5,30.8,33.8,44517.18,...,9.6,9.6,14,10.3,24.5,246,20.93,4.32,05:56,18:18
121,0,2010-05-02,61,31.6,25.6,28.0,38.6,31.7,34.1,44536.64,...,6.1,6.1,10,9.2,23.0,25,20.59,4.29,05:56,18:18
122,0,2010-05-03,63,30.8,25.8,27.5,38.8,31.7,33.7,44555.82,...,7.9,7.9,9,11.9,24.8,201,17.40,3.48,05:55,18:18
123,0,2010-05-04,53,30.1,26.1,27.8,37.8,32.2,34.3,44574.70,...,2.2,2.2,9,13.4,29.2,222,19.11,3.76,05:55,18:18
124,0,2010-05-05,53,29.2,26.0,27.5,35.9,31.8,33.5,44593.27,...,1.9,1.9,9,13.8,27.7,224,17.33,3.41,05:55,18:18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142358,26,2024-05-27,53,24.4,19.7,21.7,27.4,21.6,24.2,44928.77,...,1.4,1.4,4,11.5,25.2,213,15.43,2.97,05:48,18:17
142359,26,2024-05-28,53,26.5,19.5,22.5,31.4,21.4,24.9,44940.02,...,1.5,1.5,6,11.0,25.6,265,19.86,4.02,05:48,18:17
142360,26,2024-05-29,3,26.7,19.6,22.7,30.7,21.4,25.2,44950.82,...,0.0,0.0,0,10.9,24.8,274,22.60,4.45,05:48,18:18
142361,26,2024-05-30,51,26.3,19.9,22.8,30.7,21.4,25.6,44961.14,...,0.7,0.7,5,9.6,22.3,284,20.21,3.97,05:49,18:18
142362,26,2024-05-31,51,26.1,19.6,22.5,30.6,21.1,25.4,44970.97,...,1.1,1.1,7,10.5,24.5,300,21.75,4.18,05:49,18:18

In [11]:
weather_data_selected_df = weather_data_may_df[['sunshine_duration (s)', 'precipitation_hours (h)', 'wind_speed_10m_max (km/h)', 'et0_fao_evapotranspiration (mm)']]

In [13]:
weather_data_selected_df

,sunshine_duration (s),precipitation_hours (h),wind_speed_10m_max (km/h),et0_fao_evapotranspiration (mm)
120,40574.88,14,10.3,4.32
121,39600.00,10,9.2,4.29
122,39191.48,9,11.9,3.48
123,40046.57,9,13.4,3.76
124,40047.19,9,13.8,3.41
...,...,...,...,...
142358,27163.49,4,11.5,2.97
142359,35481.59,6,11.0,4.02
142360,38404.53,0,10.9,4.45
142361,33193.29,5,9.6,3.97
142362,38623.25,7,10.5,4.18

In [12]:
weather_data_unique_rows_df = weather_data_selected_df[~weather_data_selected_df.duplicated()]

In [15]:
weather_data_unique_rows_df

,sunshine_duration (s),precipitation_hours (h),wind_speed_10m_max (km/h),et0_fao_evapotranspiration (mm)
120,40574.88,14,10.3,4.32
121,39600.00,10,9.2,4.29
122,39191.48,9,11.9,3.48
123,40046.57,9,13.4,3.76
124,40047.19,9,13.8,3.41
...,...,...,...,...
142358,27163.49,4,11.5,2.97
142359,35481.59,6,11.0,4.02
142360,38404.53,0,10.9,4.45
142361,33193.29,5,9.6,3.97
142362,38623.25,7,10.5,4.18

In [20]:
weather_data_unique_features_df = (
    weather_data_unique_rows_df
    .groupby(
        [
            'sunshine_duration (s)',
            'precipitation_hours (h)',
            'wind_speed_10m_max (km/h)'
        ],
        as_index=False
    )
    .agg(
        et0_mean=('et0_fao_evapotranspiration (mm)', 'mean'),
        et0_std=('et0_fao_evapotranspiration (mm)', 'std'),
        sample_count=('et0_fao_evapotranspiration (mm)', 'count')
    )
)

In [21]:
weather_data_unique_features_df

,sunshine_duration (s),precipitation_hours (h),wind_speed_10m_max (km/h),et0_mean,et0_std,sample_count
0,0.00,2,34.1,3.52,NaN,1
1,0.00,5,21.7,2.20,NaN,1
2,0.00,9,6.1,1.65,NaN,1
3,0.00,9,7.8,1.73,NaN,1
4,0.00,9,10.5,1.97,NaN,1
...,...,...,...,...,...,...
12479,42052.75,0,33.7,7.44,NaN,1
12480,42061.46,0,28.7,7.03,NaN,1
12481,42064.54,3,37.5,5.57,NaN,1
12482,42144.28,1,26.0,6.86,NaN,1
12483,42149.11,1,27.6,5.74,NaN,1